apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goodmorning
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: goodmorning
    server: https://kubernetes.default.svc
  source:
    path: infrastructure/helm/goodmorning
    repoURL: https://github.com/elmerbulthuis/cpne.git
    targetRevision: main
    helm:
      parameters:
        - name: message
          value: Goodmorning!!!
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      enabled: true
