apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hi
    server: https://kubernetes.default.svc
  source:
    path: infrastructure/kustomize/overlays/hi-local
    repoURL: https://github.com/elmerbulthuis/cpne.git
    targetRevision: argo-rollouts
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
