identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBjTCCATOgAwIBAgIQAaOmGgsffjd8BgMnTqL/DzAKBggqhkjOPQQDAjAlMSMw
  IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNjA2MzAwODQw
  MTlaFw0zNjA2MjcwODQwMTlaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
  dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESg5ztGka0T78xoRe
  JILZTLXy6ShJzUKLbZq9EunVyfQLYWqHbF3/rZQoq1L0bs9sbjU3H+i1y/xFDu7S
  iNNKPqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
  VR0OBBYEFLS1eQWXO697a2oeAkGSMPc34D6oMAoGCCqGSM49BAMCA0gAMEUCIGSQ
  EZ0tmrVhim5VM2iX1oaofZw/MayBYyPi19LXIWx4AiEAgaLkbARKI5CzZ2os/JOa
  oS6898HJSl2bwnp6eEwZMgU=
  -----END CERTIFICATE-----
identity:
  issuer:
    tls:
      crtPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBsjCCAVigAwIBAgIQcNlUMubrZzgrwfHmlgGZCjAKBggqhkjOPQQDAjAlMSMw
        IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yNjA2MzAwODQw
        MzNaFw0yNzA2MzAwODQwMzJaMCkxJzAlBgNVBAMTHmlkZW50aXR5LmxpbmtlcmQu
        Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABK9lournZwef
        f6UAYYjB+vyejewjE50xoIQlsFCH2zfRVVkUkrolfAPXabdenDKf1Q/jbgtZtKIv
        B66jx7YH43qjZjBkMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEA
        MB0GA1UdDgQWBBQmTfT8VUgQH20aJp0/bCA0cc9YfTAfBgNVHSMEGDAWgBS0tXkF
        lzuve2tqHgJBkjD3N+A+qDAKBggqhkjOPQQDAgNIADBFAiAbOBcjXdLJr4+almp1
        +2UQsrc1+hDKpZ2TefMSohjxygIhAO21mTBxfl9T/m5VPg0I0Hn5d0buyWnFDVGt
        ocX73xbn
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIFxGABxTnG9fs4pBlH8kJMIft9QBJRVRzgHhXxrGymHpoAoGCCqGSM49
        AwEHoUQDQgAEr2Wi6udnB59/pQBhiMH6/J6N7CMTnTGghCWwUIfbN9FVWRSSuiV8
        A9dpt16cMp/VD+NuC1m0oi8HrqPHtgfjeg==
        -----END EC PRIVATE KEY-----
