# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  KUSTOMIZE_OVERLAYS_CRD:
    - crd-local
  KUSTOMIZE_OVERLAYS:
    - hello-local
    - hi-local
    - greeter-local
    - colors-local
    - monitoring-local
  HELM_CHARTS:
    - goodmorning

tasks:
  install:
    desc: Install everything
    cmds:
      - task: install:npm

  check:
    desc: Check everything
    cmds:
      - task: check:formatting
      - task: check:spelling
      - task: check:trivy-kustomize
      - task: check:trivy-helm

  fix:
    desc: Fix everything
    cmds:
      - task: fix:formatting

  build:
    desc: Build everything
    cmds:
      - task: build:kustomize
      - task: build:helm

  test:
    desc: Test everything
    cmds:
      - task: test:kubernetes-dry-run

  install:npm:
    run: once
    desc: Install Node.js dependencies
    sources:
      - package-lock.json
    generates:
      - node_modules/**/*
    cmds:
      - npm clean-install

  check:trivy-kustomize:
    deps:
      - build:kustomize
    cmds:
      - for:
          var: KUSTOMIZE_OVERLAYS
          as: OVERLAY
        cmd: >
          trivy config --exit-code 1 dist/kubernetes-{{.OVERLAY}}.yaml

  check:trivy-helm:
    vars:
      KUSTOMIZE_OVERLAYS:
        ref: concat .KUSTOMIZE_OVERLAYS .KUSTOMIZE_OVERLAYS_CRD
    cmds:
      - for:
          var: HELM_CHARTS
          as: CHART
        cmd: >
          trivy config --exit-code 1 infrastructure/helm/{{.CHART}}

  check:formatting:
    desc: Check formatting
    deps:
      - install:npm
    cmds:
      - npm run formatting

  check:spelling:
    desc: Check spelling
    deps:
      - install:npm
    cmds:
      - npm run spelling

  fix:formatting:
    desc: Fix formatting
    deps:
      - install:npm
    cmds:
      - npm run fix-formatting

  build:kustomize:
    run: once
    desc: Build Kubernetes manifests from kustomize
    vars:
      KUSTOMIZE_OVERLAYS:
        ref: concat .KUSTOMIZE_OVERLAYS .KUSTOMIZE_OVERLAYS_CRD
    sources:
      - infrastructure/kustomize/**/*
    cmds:
      - mkdir -p dist
      - for:
          var: KUSTOMIZE_OVERLAYS
          as: OVERLAY
        cmd: >
          kustomize build
          --enable-helm
          --output dist/kubernetes-{{.OVERLAY}}.yaml
          infrastructure/kustomize/overlays/{{.OVERLAY}}

  build:helm:
    run: once
    desc: Build Kubernetes manifests from helm
    sources:
      - infrastructure/helm/**/*
    cmds:
      - mkdir -p dist
      - for:
          var: HELM_CHARTS
          as: CHART
        cmd: >
          helm template hello ./infrastructure/helm/{{.CHART}} >
          dist/kubernetes-{{.CHART}}.yaml

  test:kubernetes-dry-run:
    deps:
      - build:kustomize
    cmds:
      - for:
          var: KUSTOMIZE_OVERLAYS_CRD
          as: MANIFEST
        cmd: >
          kubectl apply -f dist/kubernetes-{{.MANIFEST}}.yaml --dry-run=client
