resources:
  - ../../bases/gateway-api
  - ../../bases/kube-state-metrics
  - ../../bases/linkerd
  - ../../bases/cert-manager
  - ../../bases/argocd
  - ../../bases/argo-rollouts
  - ../../bases/crossplane-system
  - ../../bases/prometheus-operator
  - ../../bases/tekton-operator
  - argo
