---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-client
  name: hello-client
spec:
  selector:
    matchLabels:
      app: hello-client
  template:
    metadata:
      labels:
        app: hello-client
    spec:
      containers:
        - name: client
          image: alpine:3.24
          command:
            - sh
            - -c
            - |
              while true; do
                wget --spider http://hello.hello:8080
                sleep 5
              done
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 65534 # nobody
            runAsGroup: 65534 # nobody
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hello-client
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hello-client
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: "server"
        minAllowed:
          cpu: 10m
          memory: 10Mi
        maxAllowed:
          cpu: 100m
          memory: 100Mi
        controlledResources:
          - cpu
          - memory
        controlledValues: RequestsOnly
