---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hi-canary
spec:
  selector:
    matchLabels:
      app: hi-canary
  template:
    metadata:
      labels:
        app: hi-canary
    spec:
      initContainers:
        - name: initialize
          image: alpine:3.24
          command:
            - sh
            - -c
            - echo $MESSAGE > /srv/wwwroot/index.html
          env:
            - name: MESSAGE
              value: "Hello!!!"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: wwwroot
              mountPath: /srv/wwwroot
          securityContext:
            runAsUser: 65534 # nobody
            runAsGroup: 65534 # nobody
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      containers:
        - name: server
          image: python:3-alpine
          command:
            - python
            - -m
            - http.server
            - -d
            - /srv/wwwroot
            - "8080"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: wwwroot
              mountPath: /srv/wwwroot
          securityContext:
            runAsUser: 65534 # nobody
            runAsGroup: 65534 # nobody
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: wwwroot
          emptyDir: {}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  strategy:
    canary:
      canaryService: hi-canary-canary
      stableService: hi-canary
      steps:
        - setWeight: 25
        - pause: { duration: 5 }
        - setWeight: 50
        - pause: { duration: 5 }
        - setWeight: 75
        - pause: { duration: 5 }
        - setWeight: 100
---
apiVersion: v1
kind: Service
metadata:
  name: hi-canary
spec:
  type: ClusterIP
  selector:
    app: hi-canary
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: hi-canary-canary
spec:
  type: ClusterIP
  selector:
    app: hi-canary
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
