---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-message
spec:
  params:
    - name: message
      type: string
      description: Messag to print
      default: ""
  workspaces:
    - name: state
  steps:
    - name: write
      image: alpine:3.24
      script: |
        echo "$(params.message)" > "$(workspaces.state.path)/echo"
    - name: cat
      image: alpine:3.24
      script: |
        cat "$(workspaces.state.path)/echo"
