namespace: hello

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - applications.yaml
  - policies.yaml

configMapGenerator:
  - name: hello-wwwroot
    files:
      - index.html
