---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  retention: 1d
  retentionSize: 1GB
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 100m
      memory: 100Mi
