apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goodmorning
spec:
  destination:
    namespace: goodmorning
    server: https://kubernetes.default.svc
  source:
    path: infrastructure/helm/goodmorning
    repoURL: https://github.com/elmerbulthuis/cpne.git
    targetRevision: argo
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
