on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: go-task/setup-task@v1
        with:
          version: "3.37"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - uses: aquasecurity/setup-trivy@v0.3.1
        with:
          version: v0.71.2
      - run: task check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: go-task/setup-task@v1
        with:
          version: "3.37"
      - run: minikube start
      - run: task test

  deploy-local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: go-task/setup-task@v1
        with:
          version: "3.37"
      - run: minikube start
      - run: task build:kubernetes
      - run: >
          kubectl apply
          --server-side
          --warnings-as-errors
          -f dist/kubernetes-crd-local.yaml
      - run: >
          kubectl apply
          --server-side
          --warnings-as-errors
          -f dist/kubernetes-hello-local.yaml
